package errormsg

var (
	CANNOT_CREATE_VIDEO          = "CANNOT_CREATE_VIDEO"
	CANNOT_GENERATE_PRE_SIGN_URL = "CANNOT_GENERATE_PRE_SIGN_URL"
	CANNOT_UPLOAD_FILE           = "CANNOT_UPLOAD_FILE"
	GET_LIST_VIDEO_FAIL          = "GET_LIST_VIDEO_FAIL"
	GET_VIDEO_FAIL               = "GET_VIDEO_FAIL"
)
